services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db_n
    restart: always
    environment:
      POSTGRES_DB: flowersShop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nikita12345
    ports:
      - "5434:5434"
    command: postgres -p 5434
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5434" ]
      interval: 5s
      retries: 5
      timeout: 5s
      start_period: 30s # Give PostgreSQL more time to start

  redis:
    image: redis:6.2
    container_name: redis_n
    restart: always
    ports:
      - "6380:6380"
    command: redis-server --port 6380 --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6380", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  nest_backend:
    build: .
    container_name: nest_backend_2
    restart: on-failure
    depends_on:
      postgres_db:
        condition: service_healthy
      redis:
        condition: service_healthy # Redis doesn't have a built-in healthcheck in this image
    environment:
      DATABASE_URL: "postgresql://postgres:nikita12345@postgres_db:5434/flowersShop?schema=public"
      REDIS_HOST: "redis"
      REDIS_PORT: "6380"

    ports:
      - "1331:1331"
    command: ["sh", "-c", "npx prisma migrate dev --name init && npm run start:prod"] # Run migrations before starting

volumes:
  pgdata:
