name: CI

on:
  push:
    branches: [ main, master, developer ]
  pull_request:
    branches: [ main, master, developer ]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./FocusWord_backend_by_TypeWord

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './FocusWord_backend_by_TypeWord/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint
      
    - name: Build
      run: npm run build

    - name: Test
      run: npm test || echo "No tests specified"

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./FocusWord_client_by_TypeWord

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './FocusWord_client_by_TypeWord/package-lock.json'

    - name: Install dependencies
      run: npm ci
      
    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Test
      run: npm test || echo "No tests specified"